# Generated by Django 4.2.1 on 2023-06-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='producer',
            field=models.CharField(default='', max_length=256),
        ),
    ]
