# Generated by Django 4.2.1 on 2023-06-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_purchase_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='producer',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
